Repository commandgeek/geeksmp, pull requests merged in 2022-01, with the labels that each got.

#38 Replaced nms with ProtocolLib which should fix workflows
  .github/workflows/gradle.yml
  .github/workflows/gradle_pr.yml
  build.gradle
  src/main/java/com/commandgeek/GeekSMP/Main.java
  src/main/java/com/commandgeek/GeekSMP/managers/PacketManager.java
  src/main/resources/plugin.yml
Labels: bug, enhancement

#35 Added so undeads cant interact with item frames or use elytras
  src/main/java/com/commandgeek/GeekSMP/listeners/InteractListener.java
  src/main/java/com/commandgeek/GeekSMP/listeners/MoveListener.java
Labels: enhancement

#20 Maybe fix #3 and fix #7
  src/main/java/com/commandgeek/GeekSMP/Setup.java
  src/main/java/com/commandgeek/GeekSMP/managers/Lag.java
  src/main/java/com/commandgeek/GeekSMP/managers/ServerManager.java
Labels: bug, help wanted
