Repository commandgeek/geeksmp, pull requests merged in 2022-02, with the labels that each got.

#40 Made conduit and glow berries attainable
  src/main/java/com/commandgeek/GeekSMP/Main.java
Labels: bug, enhancement

#42 Skeleton arrow pickup and username formatting fix
  src/main/java/com/commandgeek/GeekSMP/listeners/EventListener.java
  src/main/java/com/commandgeek/GeekSMP/listeners/JoinListener.java
  src/main/java/com/commandgeek/GeekSMP/listeners/discord/DiscordMessageCreateListener.java
  src/main/java/com/commandgeek/GeekSMP/managers/ChatManager.java
  src/main/java/com/commandgeek/GeekSMP/managers/ItemManager.java
  src/main/java/com/commandgeek/GeekSMP/managers/MessageManager.java
Labels: bug

#45 Updated locked blocks list
  src/main/java/com/commandgeek/GeekSMP/managers/LockManager.java
Labels: enhancement

#46 Lockable blocks can now be specified in the config.yml
  src/main/java/com/commandgeek/GeekSMP/Main.java
  src/main/java/com/commandgeek/GeekSMP/Setup.java
  src/main/java/com/commandgeek/GeekSMP/managers/LockManager.java
  src/main/resources/config.yml
Labels: enhancement

#76 Add PlaceholderAPI support
  build.gradle
Labels: enhancement

#85 Fix #3 and add undead join/leave messages
  src/main/java/com/commandgeek/GeekSMP/Setup.java
  src/main/java/com/commandgeek/GeekSMP/listeners/JoinListener.java
  src/main/java/com/commandgeek/GeekSMP/listeners/QuitListener.java
  src/main/java/com/commandgeek/GeekSMP/listeners/discord/DiscordMessageCreateListener.java
Labels: bug, enhancement

#89 Fix #36 & remove `minecraft:` replace
  src/main/java/com/commandgeek/GeekSMP/Main.java
  src/main/java/com/commandgeek/GeekSMP/commands/CommandBypass.java
  src/main/java/com/commandgeek/GeekSMP/listeners/CommandListener.java
  src/main/java/com/commandgeek/GeekSMP/listeners/InteractListener.java
  src/main/java/com/commandgeek/GeekSMP/managers/BypassManager.java
  src/main/resources/messages.yml
  src/main/resources/plugin.yml
Labels: bug, enhancement

#100 Fix #98 and #26 + other changes
  build.gradle
  src/main/java/com/commandgeek/geeksmp/Main.java
  src/main/java/com/commandgeek/geeksmp/Setup.java
  src/main/java/com/commandgeek/geeksmp/commands/CommandAfk.java
  src/main/java/com/commandgeek/geeksmp/commands/CommandBroadcast.java
  src/main/java/com/commandgeek/geeksmp/commands/CommandRevive.java
  src/main/java/com/commandgeek/geeksmp/listeners/DamageListener.java
  src/main/java/com/commandgeek/geeksmp/listeners/DeathListener.java
  src/main/java/com/commandgeek/geeksmp/listeners/EventListener.java
  src/main/java/com/commandgeek/geeksmp/listeners/InteractListener.java
  src/main/java/com/commandgeek/geeksmp/listeners/JoinListener.java
  src/main/java/com/commandgeek/geeksmp/listeners/QuitListener.java
  src/main/java/com/commandgeek/geeksmp/listeners/discord/DiscordMessageCreateListener.java
  src/main/java/com/commandgeek/geeksmp/managers/ChatManager.java
  src/main/java/com/commandgeek/geeksmp/managers/LinkManager.java
  src/main/java/com/commandgeek/geeksmp/managers/ListManager.java
  src/main/java/com/commandgeek/geeksmp/managers/LockManager.java
  src/main/java/com/commandgeek/geeksmp/managers/MessageManager.java
  src/main/java/com/commandgeek/geeksmp/managers/MorphManager.java
  src/main/java/com/commandgeek/geeksmp/managers/TeamManager.java
  src/main/resources/config.yml
  src/main/resources/messages.yml
  src/main/resources/plugin.yml
Labels: bug, enhancement

#104 Minor changes
  build.gradle
  src/main/java/com/commandgeek/geeksmp/listeners/BlockListener.java
  src/main/java/com/commandgeek/geeksmp/listeners/InteractListener.java
  src/main/java/com/commandgeek/geeksmp/listeners/discord/DiscordMessageCreateListener.java
  src/main/java/com/commandgeek/geeksmp/managers/BypassManager.java
  src/main/java/com/commandgeek/geeksmp/managers/ChatManager.java
  src/main/java/com/commandgeek/geeksmp/managers/ConfigManager.java
  src/main/java/com/commandgeek/geeksmp/managers/TeamManager.java
  src/main/resources/messages.yml
Labels: bug, enhancement

#107 Fix #103, broken message keys, and Discord -> MC chat
  src/main/java/com/commandgeek/geeksmp/Setup.java
  src/main/java/com/commandgeek/geeksmp/listeners/EventListener.java
  src/main/java/com/commandgeek/geeksmp/listeners/JoinListener.java
  src/main/java/com/commandgeek/geeksmp/listeners/discord/DiscordMessageCreateListener.java
  src/main/java/com/commandgeek/geeksmp/managers/ChatManager.java
  src/main/java/com/commandgeek/geeksmp/managers/LockManager.java
  src/main/java/com/commandgeek/geeksmp/managers/TeamManager.java
  src/main/resources/messages.yml
Labels: bug
